spring.application.name=snippet-manager

# spring.datasource.url=jdbc:postgresql://localhost:5432/snippet_db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 In-Memory for demo
spring.datasource.url=jdbc:h2:mem:snippet_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Allow CORS for development
spring.mvc.cors.allowed-origins=http://localhost:5173
